"""Add tg_id column

Revision ID: c5c0f5fd4bd3
Revises: 499346fa02c0
Create Date: 2025-01-16 08:49:21.017253+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "c5c0f5fd4bd3"
down_revision: Union[str, None] = "499346fa02c0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("tg_id", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "tg_id")
